<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Dn_Testimonial::css/styles.css')?>">
<?php
$testimonial = $block->getCollection();
$testimonialData = $testimonial->getData();
?>
<div class="widget block block-static-block testemonials-widget">
    <div class="block-title"><strong>Depoimentos</strong></div>
    <ul class="testemonials-list">
        <?php foreach ($testimonialData as $testimonialItem) : ?>
            <li class="testemonial">
                <div class="testemonial-content">
                    <div class="image">
                        <img src="<?php echo $this->getAvatarUrl($testimonialItem['avatar']); ?>" width="100" height="100" />
                    </div>

                    <div class="content">
                        <?php if ($testimonialItem['name']) : ?>
                            <h3 class="name"><?= $testimonialItem['name']; ?></h3>
                        <?php endif; ?>

                        <div class="description">
                            <?php if ($testimonialItem['content']) : ?>
                                <p class="text"><?= $testimonialItem['content']; ?></p>
                            <?php endif; ?>
                        </div>

                        <?php if ($testimonialItem['testimonial_date']) : ?>
                            <?php
                            $date = $testimonialItem['testimonial_date'];
                            $dateFormat = $this->timezone->date(new \DateTime($date))->format('d/m/Y');
                            ?>
                            <p class="date"><?= $dateFormat ?></p>
                        <?php endif; ?>

                    </div>
                   
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
